# Your presentation title
title: Teaching and Viz Jekyll and Reveal.js

# Your presentation description (optional)
description: A framework for easily creating beautiful presentations using HTML that fits NCSU Libraries Teaching and Vizualization Studio

# Your name (optional)
author: jekyll-revealjs contributors

# The Reveal theme
reveal_theme: black.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 
    width: 16384   # Change this to fit the entire studio only if its off
    height: 1200   # Same as width.
    transition: fade  # none, fade, slide, convex, concave and zoom.
    transition_sped: slow  # default, fast, slow

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme

# You can choose from none, fade, slide, convex, concave and zoom.

